### ISSUE TITLE
Duplicated name! What can we do?

### ISSUE THREAD

**Issue by philocoder** [friedrith/natural-script#1]
Hello!

I'm the (...first?) NaturalScript Language creator. Well, or a second one, I don't know, I don't really mind.

This is it:

http://naturalscriptlanguage.com/

I don't know, I don't really care about changing the name, despite the domain.... But, well... just to say "hello".

Well, in fact, if you are really into this thing of the language, maybe we can talk a little about the current state of the art. It would be great to share and interchange views. Independently of the "names issue", I don't really mind about the name, even if you are interested in the domain we can talk

**Comment by thibaultfriedrich** [comment]
Hi NaturalScript Language creator!

Sorry about that, I did a little check before using this name but I didn't find your website. Maybe you should work on your SEO to have a better visibility on search engines. It is only an advice and in no way a reproach. On my side, I cheated by using npm which is is an overkill SEO booster ;)

You are without doubt the first.  You have several months of anteriority.

However because of I am using npm I would prefer this name for retrocompatibility issues. I don't see any problems for each of us to keep this name. It is only a side project for me so I don't plan to use the domain name. Moreover, except if the project very famous, I don't plan to expand. For now, I only use this github, npm and my demo website [ns.techmind.io](http://ns.techmind.io). Anything else if for you including the domain name. Did you plan to use npm ? If it is the case, maybe I should reconsider using *natural-script* name. 

If you are ok, I might add a warning on my repository description to explain that it is not linked to your project.

In any case, thanks for the "ping" !

And yes, I am interesting to talk with you about the state of the art. It might be very interesting!

Good luck!
